[project]
name = "est"
version = "0.1.0"
description = "Estate Service"
authors = [
    {name = "Evgeny Bilim",email = "evgenybilim@gmail.com"}
]
readme = "README.md"

requires-python = ">=3.12"
dependencies = [
    "alembic (>=1.14.0,<2.0.0)",
    "fastapi (>=0.115.6,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "pydantic-settings (>=2.7.1,<3.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "psycopg (>=3.2.3,<4.0.0)",
    "greenlet (>=3.1.1,<4.0.0)",
    "orjson (>=3.10.18,<4.0.0)",
    "sniffio (>=1.3.1,<2.0.0)"
]

[tool.mypy]
explicit_package_bases = true
mypy_path = "."
plugins = ["sqlalchemy.ext.mypy.plugin", "pydantic.mypy"]
disable_error_code = ["var-annotated"]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.5.1"
ruff = ">=0.14.11,<0.15.0"
mypy = ">=1.19.1,<2.0.0"
sqlalchemy = {extras = ["mypy"], version = "^2.0.48"}
pydantic = {extras = ["mypy"], version = "^2.12.5"}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.format]
exclude = ["src/application/seeder/const.py"]

[tool.ruff.lint]
select = [
    "E", "F", "C90", "I", "N", "UP", "YTT", "ASYNC", "S", "B", "C4", "DTZ", "T10", "ISC", "ICN",
    "PIE", "T20", "PT", "Q", "RET", "SLF", "SIM", "ERA", "PLE", "TRY", "PYI", "PERF", "LOG", "RUF008",
    "RUF009", "RUF012", "RUF013", "RUF015", "RUF019", "RUF100", "RUF200",
]
unfixable = ["ERA"]
ignore = ["UP040", "TRY003", "ISC001"]

[tool.ruff.lint.mccabe]
max-complexity = 50

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S", "C4", "ISC", "SLF", "RUF012"]
"src/*" = ["PT"]
"src/application/seeder/*" = ["S"]
"src/app/http.py" = ["S104"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "pydantic.validator",
    "pydantic.root_validator",
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.Form", "fastapi.Body"]
