"""add group plans

Revision ID: 5c835c2fdfc1
Revises: 7245a9fe8bc0
Create Date: 2026-04-15 22:18:25.845708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c835c2fdfc1"
down_revision: str | None = "7245a9fe8bc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_groups",
        sa.Column("plan_uuid", sa.UUID(), nullable=False),
        sa.Column("group_uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["plan_uuid"], ["plans.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("plan_uuid"),
    )
    op.create_index(op.f("ix_plan_groups_group_uuid"), "plan_groups", ["group_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_groups_group_uuid"), table_name="plan_groups")
    op.drop_table("plan_groups")
    # ### end Alembic commands ###
